### ISSUE TITLE
Data Validation

### ISSUE THREAD

**Issue by pedrovt** [pedrovt/ams_g01#10]
On Create/Edit Event : -> start date <= end date; change number of participants can't be allowed if the current number of participants is superior to the wanted limit
On Add Participants : Only possible within the limit of participants defined in event info

**Comment by pedrovt** [comment]
no duplicated events, etc

**Comment by pedrovt** [comment]
can't acess pages like create documents for example when an event does not exist

**Comment by ZePaiva** [comment]
It's impossible to access create documents of non existent events.
Closing the issue
