### ISSUE TITLE
create documents

### ISSUE THREAD

**Issue by pedrovt** [pedrovt/ams_g01#8]

**Comment by ZePaiva** [comment]
Create documents API is now available in webproj/documents/doc_gen.py. Can be tested with webproj/test_docs.py

**Comment by pedrovt** [comment]
missing actual document creation and update DB (table documents, columns e_name, name [of the document, can be auto-generated by anyway you want], type[health/safety/...], path)

**Comment by ZePaiva** [comment]
Document creation and storage is now fully functional.
Closing this issue.
